### ISSUE TITLE
angular12-microfrontends - shared deps packaged twice ?

### ISSUE THREAD

**Issue by raphael22** [module-federation/module-federation-examples#1227]
Hello there.
I notice that webpack bundle shared dependencies into main.js but also in polyfills.js :
Resulting a 800kb build.
![image](https://user-images.githubusercontent.com/3912356/137697985-7b02d631-717d-492f-86a2-08c1b102be6f.png)

The way to go would be to set eager to false then ?
Down the build half size.
![image](https://user-images.githubusercontent.com/3912356/137698050-410d64b1-b925-4fe3-b520-0b007e9bbe1c.png)

But we get the eager error
![image](https://user-images.githubusercontent.com/3912356/137698376-e96dbf01-f3b6-440b-9fa6-b31460db58ca.png)

I'm struggle a bit to find the good configuration for having both world, a shell which consume and expose singleton deps.

**Comment by nohanna** [comment]
I have the same issue with the polyfills, a simple app will result in a large bundle because of this.
The problem is, if you don't have your shared deps added eagerly, you will have to change your app bootstrap.
I didn't find a solution yet, but I guess that in Angular, we have to set eager to true for now.

But why is webpack adding everything in main.js **and** polyfills?

**Comment by raphael22** [comment]
@nohanna Good news !
I finally find a solution to make it work with **eager: false**.

As indicate [here ](https://webpack.js.org/concepts/module-federation/#uncaught-error-shared-module-is-not-available-for-eager-consumption) I switch from static bootstrap import:
  ```import "./bootstrap";``` 
to dynamic one: 
  ```import('./bootstrap');```

Making the final build working with only one copy of deps instead of two.
Still struggling to make it work without eager or to bundle some deps to avoid having one endpoint per deps  thought.
