### ISSUE TITLE
HMR with multiple remotes

### ISSUE THREAD

**Issue by sexta13** [module-federation/module-federation-examples#1290]
Hey,

I've tried to use HMR with multiple remotes, but it seems that only the first one that is loaded has the HMR working. The rest updates the source (I can see in devtools the file updated) but it doesn't update the layout.

@burhanuday did you manage with multiple remotes? can you add an example ?

Thanks and merry xmas.

**Comment by ScriptedAlchemy** [comment]
Hot reloading is extremely complex and would require changes to webpack. 

HMR works over a socket by broadcasting graph updated to the runtime. In order for it to work would require that webpack is aware of all module graphs from all remotes. 

Webpack has to know who's consuming the module (parent) since memory references exist so child and parent module have to be hot reloaded
