### ISSUE TITLE
Caching problems

### ISSUE THREAD

**Issue by ruifernando7** [module-federation/module-federation-examples#1731]
I have 2 applications. 
- Host app
- App 1 

Both applications are successfully deployed on the server and host app able to use shared component from App 1.
But when i made a change on App 1 and already deployed on the server. Some how the host app not fetching the latest shared component from App 1.

When i take a look on the network, the `remoteEntry.js` and chunks from App 1 are loaded from `disc cache` & `memory cache`. So when i try to refresh the host app, it still renders old component. How can i fix that? Thanks for the help

**Comment by taylorlroberts7** [comment]
@ruifernando7 You likely need to invalidate the cache. If you're using CloudFront, you can create invalidations for your Host's `index.html` file _and_ your `remoteEntry.js` files. This is necessary because the `remoteEntry.js` file doesn't contain a content hash like standalone SPAs usually do. I found this blog post that has some more useful details that will hopefully help you!
[Micro Frontends Hosting and Deployment](https://engineering.telia.no/blog/micro-frontends-hosting-and-deployment)

**Comment by ScriptedAlchemy** [comment]
I put a date stamp query string on the end of the remote url so it always is invalidated
