### ISSUE TITLE
Working with multiple copies of remote

### ISSUE THREAD

**Issue by vikkrantxx7** [module-federation/module-federation-examples#1837]
I am working on a use case where we have multiple copies of remote hosted and I want to include them in the host.

Problem - 
When the initial remote is loaded then clicking on the button to load the copy of the remote did not flush the webpack references and hence I have to reload the browser every time the remote copy is loaded.

I have this remote configuration-
```
"remote": {
      "url": "https://localhost:8080/bundle.js",
      "scope": "ScopeName",
      "module": "./ModuleName"
    },
"remoteCopy": {
      "url": "https://localhost:8070/bundle.js",
      "scope": "ScopeName",
      "module": "./ModuleName"
    },
```
Changing the scope name or module name is not working as the internal references are retained.

In webpack config of remote-

```
new ModuleFederationPlugin({
      name: 'ScopeName',
      filename: 'bundle.js',
      library: { type: 'var', name: 'ScopeName' },
      exposes: {
        './ModuleName': './src/main'
      })
```

**Comment by vikkrantxx7** [comment]
I found out this issue was due to the same package name in package.json for both bundles.
But the package name will be anyways same for the same repo.

**Comment by ScriptedAlchemy** [comment]
you'd need to namespace the remotes (give them a unique name) in order to avoid collisions on the global object.

You cannot flush refs out of webpack easily, objects get copied deeply into the module graph and this can cause strange side effects. If you need different versions of a remote, the best solution is to reference "versioned remotes" like remote: remote_v123@http:////

And 

Remote: remote_v567@http:///

**Comment by vikkrantxx7** [comment]
As I mentioned above changing the scope name and module name did nothing.

The thing that worked for me was using output.uniqueName and change it for every package.

**Comment by ScriptedAlchemy** [comment]
https://medusa.codes/
