### ISSUE TITLE
Amount of generated chunks based on shared configuration

### ISSUE THREAD

**Issue by slavab89** [module-federation/module-federation-examples#1851]
We've started migrating our codebase to use module federation.

I wanted to ask and see if its possible to somehow control the behavior that Federation creates for chunks.

To my understanding (And from what I see happens), each dependency I put in the "shared" part creates an async chunk. Especially if it is also marked as Singleton.
This means, that if we have 10+ 20+ modules that are "singleton", each one of them will be in its own chunk = its own file. Examples are React modules that use Context.
Quite a few of those modules are common that should be loaded right at the beginning.
Is there a way to combine them to the same chunk? While still preserving the webpack sharing context capabilities? 

1. Having them together via splitChunks plugin seems to take them out of the webpack/sharing context and they are loaded once more.
2. It possible to mark them as "eager" to force them to be part of the initial chunk (Only on the host), but this again seems to break other remotes due to load order (race conditions on who loads what and who expects what).
3. Load remotes using "dynamic" promise new Promise way - what we currently do but it forces the application parts to load in a specific sync way. I cannot load any remote until the host has "finished" loading

**Comment by ScriptedAlchemy** [comment]
You can "sideload" modules into share scope

Like object.assign(__webpack_share_scopes__.default) - its usually not something i recommend but its useful if you want to provide "host only" modules that are not marked as eager. Leaving the modules in the graph where they normally would be. 

Yes you can enforce a policy on splitChunks for force modules into a single chunk of aggregate one to many which is helpful. I often use this to ensure that im not loading dozens of like 1kb files but rather id load a 20kb chunk with several exposed modules in it. 

There's some documentation online about splitChunks and Module Federation 

Hmm promise new promise would likely have the same issues that global@remoteUrl would, since under the hood its more or less the same mechanics - just when a promise is passed, you're the one injecting the tag. Still the host has to "boot" and remotes are only loaded on-demand (as the host is booting and iterating over its module map) 

Id suggest looking at some server-side logic if you want to speed up the boot sequence and get the right files on the page upfront. Then your promise new promise could just read a inline json reference for instructions on what you'd pass from server-side.

**Comment by slavab89** [comment]
Thanks a lot for the answer! If I may, I would like to ask something that is somewhat related to the same topic.

So let’s say we have a federated module for UI components, we have a Button, TextField and Toggle.
I know that I would likely always need and use Button and TextField in the same place but Toggle will have seldom usage.

All 3 components would be exposed separately, probably, so it will create 3 JS files. It means that when I’ll use Button and TextField I would have to download 2 remote files.

Anything that can be done I’m order to somehow combine them and to 1 exposed file?  While still being able to import each component and use it.

The main reason that I’m asking this is due to the fact that browsers can download only 6 files in parallel from a domain, and if I’m exposing several components that I know will be used together and each of them has some other 3rd party modules it uses, it may create quite a lot of files and would take some time to download all of them

**Comment by ScriptedAlchemy** [comment]
Customize splitChunks and use enforce:true, you can force modules back into fewer chunks
