### ISSUE TITLE
Issue with route sharing between host and inner apps

### ISSUE THREAD

**Issue by morleytatro** [module-federation/module-federation-examples#1933]
I'm trying to set up a basic host app which shares routing with two inner apps. I've bumped into a few snags which are probably user error:
- switching between the `dashboard` and `marketplace` routes leads to this error and a seeming dismount of some of the children: https://github.com/facebook/react/issues/23202
- I can't seem to load the two inner apps synchronously without using `lazy` even though I've established an async boundary.
- I'm seeing some dependency duplication in the console even though I'm attempting to share them.

https://github.com/morleytatro/module-federation

Is there anything obviously wrong with the Webpack configs? Thanks!

**Comment by ScriptedAlchemy** [comment]
hmm interesting. I see this is using react 18. 

ive cloned your repo and will try to see whats going on here, cant see anything immediately wrong. im wondering if maybe you should set the container app to share these modules with eager:true, since its always the host and you basically want to force those singletons to come from the parent application. 

Remotes not eager, host eager, remote loads shared module async only if needed, host provides shared modules upfront that it has
