### ISSUE TITLE
Material classnames overriding each other in MF Application in production

### ISSUE THREAD

**Issue by palnic-chisel** [module-federation/module-federation-examples#1954]
I got two microfrontend using Material 4 as CSS Framework. It changes its classnames in production mode. For example "Mui-Root xxx" could be "jss1" and so on.
It happens randomly that I got "jss1" from app1 attached to a component (of the same type, meaning have Box component in both app1 and app2) in app2, and it shouldn't be like this. I lost control of my styles.
It's very hard to reproduce it in a snippet, but I think the solution would be try to force material to customize its renaming logic. 
Any ideas how to do it? I tried with generateClassName + StylesProvider but it seems not working at all.
Is there any other way (maybe sharing some dependencies from webpack.config) to achieve this?

**Comment by dimitri-HR** [comment]
This is how I use it in Material UI 4

``` js
// AppRoot.jsx
import { createGenerateClassName, StylesProvider, ThemeProvider } from '@material-ui/core/styles'

const generateClassName = createGenerateClassName({
  productionPrefix: 'c360-',
  seed: 'c360',
})
...
const AppRoot = () => (
      <ThemeProvider theme={theme}>
        <StylesProvider generateClassName={generateClassName}>
            // ...the rest of the app, e.g. <App />
        </StylesProvider>
      </ThemeProvider>
)
```

In Material UI 5 things changed.  You likely need something like this: 
https://mui.com/material-ui/experimental-api/classname-generator

It can add unique prefixes to all MaterialUI default classes in each Microfrontend (e.g. MuiBox-root, MuiTypography, etc). This way your MFEs classnames won't collide.

``` js
// do this for each of your micro app
// AppRoot.jsx
import { unstable_ClassNameGenerator as ClassNameGenerator } from '@mui/material/className'

// NOTE: add css prefix to Mui components only (e.g. not to developer-generated classnames)
ClassNameGenerator.configure(componentName => `rootapp-${componentName}`)

const AppRoot = () => {
...
}
```

However it doesn't add anything to your own css classes. 
For example when you're using it like in the code below, the prefixes are not added.
```js

const styles = {
  headerContainer: {
    display: 'flex',
   ...
  },
}

const AppRoot = () => {
   ...
  return (
    <Box sx={styles.headerContainer}>... </Box>
  )
}

```
I found that I could use emotion `createCache` if I need to prefix my own classes:

```js
import { CacheProvider } from '@emotion/react'
import createCache from '@emotion/cache'
import { ThemeProvider } from '@mui/material/styles'

// NOTE: add css prefix to all developer-generated styles
const stylesCache = createCache({ key: 'rootapp-' })

const AppRoot = () => {
  <CacheProvider value={stylesCache}>
    <ThemeProvider theme={theme}>
      <App  />
    </ThemeProvider>
  </CacheProvider>
}

```
This works fine... 

However I still prefer Material UI 4 way because the names of the classes it generated were more user friendly and I could easily see and recognise them in generated code. 

With Material UI 5 they are all cryptic now unfortunately   😢 

Hope this is useful. 

If somebody has a better way of dealing with this problem, please share 😃

**Comment by ScriptedAlchemy** [comment]
make the share key for mui this

"@mui/": {whateverShareOptions}

**Comment by dimitri-HR** [comment]
@ScriptedAlchemy Hey Zack, not very sure what you mean... Can you elaborate please ;-)

**Comment by danielkeva** [comment]
> make the share key for mui this
> 
> "@mui/": {whateverShareOptions}

Correct me if I'm wrong but it would  disable the tree shaking from the shared library right?

**Comment by ScriptedAlchemy** [comment]
anything shared already opts you out of tree shaking those dependencies.

**Comment by ScriptedAlchemy** [comment]
Theres likely a better way than trailing slash on all of mui, but someone would need to trace what exactly needs to be shared. Feel free to PR the readme about MUI or update this issue if anyone finds a less nuclear solution
