### ISSUE TITLE
Why load the shared library from remote in module federation?

### ISSUE THREAD

**Issue by cp3hnu** [module-federation/module-federation-examples#2065]
<img width="811" alt="截屏2022-07-09 17 56 43" src="https://user-images.githubusercontent.com/6104542/178100910-bf20a849-9b1a-4549-a8fd-02f87dbc6488.png">
<img width="809" alt="截屏2022-07-09 17 57 03" src="https://user-images.githubusercontent.com/6104542/178100911-08bb34dc-0d3e-43ba-88af-ca13561b92b1.png">

In Module Federation example https://stackblitz.com/github/webpack/webpack.js.org/tree/master/examples/module-federation?terminal=start&terminal=.
Why load shared library from remote in module federation?
Shared libraries should not be loaded from host for performance？

**Comment by ScriptedAlchemy** [comment]
Its loaded based on semver rules and whoever has the best version to serve the needs of the apps. 

Webpack decides, its not always the host that loads the shared dep and usually has no perf hit since either way its an async chunk that needs to be loaded, either from host build or another build. But its a network request either way

**Comment by ScriptedAlchemy** [comment]
So I workaround to prioritize shared modules from the host is to set version on the shred module to something lower. Like I'll set mine to 0, so webpack picks the higher version because the host needs that, but if one doesn't exist or running standalone. Webpack can still use its remote as like a secon priority load
