### ISSUE TITLE
Issue with NextFederationPlugin for react-host, nextjs-remote

### ISSUE THREAD

**Issue by yangchoo** [module-federation/module-federation-examples#2254]
Hi there, thanks for the fantastic work on this plugin.

I'm in the process of upgrading from v3.3.0 to v5.1.2 for an environment which uses a react-host and nextjs-remote.

However, I'm running into issues doing so and have narrowed it down to this specific error
```
Uncaught (in promise) Error: Shared module next/head doesn't exist in shared scope default
```

Here is the minimally reproducible example based off the current example listed in this repo:
https://github.com/module-federation/module-federation-examples/compare/master...yangchoo:module-federation-examples:yang-upgrade-mf-plugin

Note that the issue only presents itself when resolving the remote page (presumably because of the `next/head` import), while federation is otherwise working for the remote component.

Will appreciate any help you can provide here, thank you!

**Comment by ScriptedAlchemy** [comment]
Send a PR.

By default i mark next remote builds as import:false when sharing.

You can add an option like `includeNextInternals` which removes me setting import = false on the reduce loop. 
Or you can add options like `skipSharingNextInternals` which prevents me from sharing those next/ packages at all - then they wont need to be in share scope.

When running a next host, the next internals in remote must be import: false otherwise webpack attempts to load two copies because there's no async boundary in next to allow webpack to negotiate shared modules that are internal in next
