### ISSUE TITLE
Bust cached remoteEntry.js file

### ISSUE THREAD

**Issue by Dilatorily** [module-federation/module-federation-examples#233]
Is there a way to bust a cached version of the `remoteEntry.js` file without rebuilding the host?

If so, can we get an example on how it can be achieved?

**Comment by ScriptedAlchemy** [comment]
dynamically inject it or use a querystring along with a preload tag
![image](https://user-images.githubusercontent.com/25274700/89091947-71ef8600-d362-11ea-8d3d-1cd5d790577d.png)


Use the CDN and cache-control headers

OR 

During CI, write a JSON map of cache busted file names to look up and inject (can increase RTT)

**Comment by arshita04** [comment]
@ScriptedAlchemy can you share an example of how to bust cache once the app that we are consuming in the host gets updated.

**Comment by ScriptedAlchemy** [comment]
Inspect lululemon's website. We have like 4 federated containers all cache busting, been in prod for well over a year

**Comment by arshita04** [comment]
Thanks, will do! Just a quick followup, is there a way to implement fingerprinting for caching to save us round trips, while implement dynamic remotes.

**Comment by ScriptedAlchemy** [comment]
If you can figure out the script and server side render it in the markup ahead of time.

**Comment by jcmillett** [comment]
I'm working with module federation, and cache busting the remoteEntry file(s) was a concern I had. However, I noticed through looking at Chrome's devtools that the remoteEntry file never seems to be cached, it fetches it every time. That's without me making any special changes to apply cache busting.

I don't have the remoteEntry file listed as a script tag in the HTML for my primary host app, instead, I'm just using the remotes section in my webpack config file within the module federation plugin. With this setup, it appears that webpack and/or the module federation plugin asynchronously loads the remoteEntry file, and that's why it's not cached. That said, can I be sure that the remoteEntry file won't be cached with this setup, or should I try to setup cache busting anyways?

**Comment by ScriptedAlchemy** [comment]
If dev tools is open it might just be you have disable cache box ticked. Fine for dev mode but in production you'll want some kind of cache bust technique, weather its a time stamp or something a little more robust / etag CDN invalidate headers

**Comment by jcmillett** [comment]
Gotcha, yeah I normally disable the cache in the devtools using that checkbox, but for this specific test, I had unchecked it. Some of the other static assets were being served up from the cache according to the devtools but not remoteEntry.js, which is what I thought was strange and why I figured I'd ask.

I'll just play it safe though and cache bust using a query string along with the `external-remotes-plugin`. Thanks for the response.
