### ISSUE TITLE
[Question] When do I need eager:true? Is there anything I can do to avoid creating an async entry like bootstrap?

### ISSUE THREAD

**Issue by MrBlackoct** [module-federation/module-federation-examples#2447]
Hey there, I wonder know when do I need eager:true? 

I\`ve always seen eager:true as a way to avoid creating an async entry like bootstrap. In ModuleFederationPlugin docs and other blogs, eager:true and async entry are 2 optional choose for eager consumption Error. Is that means eager:true is a substitution of async entry?

I\`ve tried like follows:
```js
// Host without async entry
{
    shared: {
        "react": {
          eager: true,
        },
        "react-dom": {
          eager: true,
        },
      }
}
```
And I still got eager consumption Error.

If there is no shared lib in Host app config, it will works just fine without async entry.

Also, I\`ve read some blogs said:
> If one lib set eager:true, ... All possible shared modules need to be eager too.
Is that true?

Really appreciate if you can help me out.

**Comment by ScriptedAlchemy** [comment]
No they don't all need to be eager. That's actually not a good move. Eager should be used a little as possible. 

Async bootstrap is a catchAll. Webpack hoists the sync import to the nearest parent dynamic import. If you share react then usually your entrypoint imports react. So the only parent would be the async bootstrap where webpack can pause app and resolve chunks. 

So you just need a dynamic import in the tree somewhere before you require or import from the shared module. 

Eager moves the dependency into the remote itself so that it's always available upfront

**Comment by ScriptedAlchemy** [comment]
Async boundary will no longer be needed in the next release. 
https://github.com/module-federation/universe/pull/1639

You currently can enable it if you use AsyncBoundaryPlugin which is in /enhanced package
