### ISSUE TITLE
How to copy static files from one server to the other

### ISSUE THREAD

**Issue by nandeshwarshubh** [module-federation/module-federation-examples#2645]
So, I have two microfrontends using MF

MFE1 - shell microfrontend
     /public/mfe1assets/{name}.png
MFE1 is deployed on 11.22.33.44

MFE2 - child microfrontend
     /public/mfe2assets/{name}.png
MFE2 is deployed on 55.66.77.88

When I deploy these on servers, I have to manually copy all assets for MFE2 i.e.  MFE2/public/mfe2assets to MFE1/public/mfe2assets for it to work

Do we have any plugin that loads the static assets for child microfrontend to parent similar to remoteEntry for js files.

**Comment by nebarf** [comment]
@nandeshwarshubh I guess the resolution fails because you're referencing assets by using relative paths. What about using a loader to perform a relative-to-absolute path mapping at build time?

A webpack config which use a combination of a dynamic [public path](https://webpack.js.org/guides/public-path/) and [file loader](https://webpack.js.org/guides/asset-modules/) should do the trick.

**Comment by ScriptedAlchemy** [comment]
PostTransformPublicPath on a loader would solve this. Like file loaders public path function. So that it's not relative but can do some lookup at runtime and resolve proper paths. 

If loader supports public path auto then it would work out the box same way webpack doesn't need hard coded urls for chunk loading
