### ISSUE TITLE
Federated Unit Tests - Error with @testing-library/react

### ISSUE THREAD

**Issue by alexis-regnaud** [module-federation/module-federation-examples#2789]
I am trying to include Federated Unit tests.

I read that [article](https://scriptedalchemy.medium.com/module-federation-how-do-we-create-unit-tests-for-it-bd0d73c999bc) posted two years ago by @ScriptedAlchemy, got that [repository](https://github.com/module-federation/reunited) on my local, and run `npm run test`. 
Everything is working correctly. But when I try to replace `Enzyme` render by a `@testing-library/react` render, I meet that issue : 

![Screen Shot 2023-02-28 at 3 11 01 PM](https://user-images.githubusercontent.com/15250423/221969163-d3014207-3e7a-45a2-a169-a5f728f89429.png)

I have forked the previous repository: https://github.com/alexis-regnaud/module-federation-testing-library 

Has anyone successfully run federated unit tests with the Jest and Testing library?
Also it could be useful to have an example within [module-federation-examples](https://github.com/module-federation/module-federation-examples)

**Comment by ilteoood** [comment]
Hi @alexis-regnaud!
I'm developing a dedicated plugin for federated tests: https://github.com/ilteoood/native-federation-tests

Would you like to give it a try?

**Comment by ScriptedAlchemy** [comment]
this is because you are mixing imports - youre requiring esm babel utils and its not going through transpiles. 
so either esm needs to transpile it on the fly, or you need the CJS version to be used. 

Jest in general doesn't work with ESM, so any package thats esm based has to be transpiled again. 

as for testing federation in general, we are working on a jest transformer so that webpack is infront of a test that uses federated imports. 
The issue shown in the screenshot however is not a federation problem - just plain old ESM trying to be required which wont work.
