### ISSUE TITLE
Possible dynamic import on the remote module?

### ISSUE THREAD

**Issue by sercan5534** [module-federation/module-federation-examples#2800]
I want to import images dynamically which are inside a folder on my Icon component - it's a remote component shared by Shared-app - like this:

```
 const importIcon = (name: string) => {
        import(
            /* webpackChunkName: "icon" */
            `../../assets/img/icon/${name}.svg`).then(res => {
                console.log(res.default)
                setIconUrl(res.default)
            })
            .catch(e=>{
                console.error(e);
            });
    }
```

And it's my Shared App's web config:
```
module.exports = {
    entry: './src/index.js',
    mode: 'development',
    devtool: 'hidden-source-map',
    devServer: {
        port: 3001,
    },
    output: {
        publicPath: 'auto',
        clean: true,
        filename: '[name].[contenthash].js',
    },

    resolve: {
        extensions: ['.tsx', '.ts', '.js', '.json', '.css', '.scss', '.jpg', '.jpeg', '.png', '.svg','.gif'],
    },
    optimization: {
        splitChunks: {
            chunks: 'async'
        }
    },
    module: {
        rules: [
            {
                test: /\.tsx?$/,
                exclude: /node_modules/,
                loader: 'ts-loader'
            },
            {
                test: /\.(jpg|png|gif|jpeg|svg)$/,
                loader: 'url-loader',
            },
            {
                test: /\.css$/i,
                use: ['style-loader', 'css-loader'],
            },
            {
                test: /\.jsx?$/,
                loader: 'babel-loader',
                exclude: /node_modules/,
                options: {
                    presets: ['@babel/preset-react'],
                },
            },
        ],
    },
    plugins: [
        new FederatedTypesPlugin.FederatedTypesPlugin({
            federationConfig: {
                name: 'shared_app',
                filename: 'remoteEntry.js',
                shared: {
                    ...deps,

                    'styled-components': {
                        singleton: true, requiredVersion: "5.3.6"
                    },
                    'react-router-dom': {
                        singleton: true, requiredVersion: "6.8.1"
                    },
                    'react-dom': {
                        singleton: true, requiredVersion: "18.2.0"
                    },
                    react: {
                        singleton: true, requiredVersion: "18.2.0"
                    },
                },
                exposes: {
                    './Card': './src/components/card/index.tsx',
                    './assets': './src/assets',
                    './Loading': './src/components/loading/index.tsx',
                    './Icon': './src/components/icon/index.tsx',
                    './Input': './src/components/input/index.tsx',
                    './Button': './src/components/button/index.tsx',
                    './Logo': './src/components/logo/index.tsx',
                    './CodeInput': './src/components/codeInput/index.tsx'
                }
            }
        })
    ],
};
```
But when I'd like to use this component on another micro-frontend app, I get an error like this:
![Screen Shot 2023-03-03 at 13 17 23](https://user-images.githubusercontent.com/1253763/222694726-74359f08-5f26-433d-9171-5a705b84c23e.png)

So I don't use it :( I investigated the web pack output, but I can not find any clue depending on the images.
Is there any trick to using images in this way?

**Comment by brunos3d** [comment]
Hello, @sercan5534. Imagine that what you are doing with Module Federation is just separating a slice of your javascript code to be used by (and executed) on other applications. So think with me, your code should be ready to be consumed or receive context from different environments.

Now let's look at your case:
I suppose you have two **remotes**, let's assume that one runs on port 3001 and it's your shell/main app (app1) and another one on 3002 (app2) it is the remote that exposes and shares the components with app1.
So when your code runs on your app2 it will try to find the assets served at http://localhost:3002/assets/img/icon/Alert.svg because it's using the **relative url** that corresponds with your server running on localhost:3002, BUT when the same code runs on the browser in your application served at localhost:3001, the same code will try to use the relative path but as the files are not delivered by your server on 3001 you will get this 404 related errors.
So we have 2 quick ways to resolve this situation:
- Use absolute URLs on your `importIcon` function
- Make your `importIcon` function be able to receive the full icon path from the arguments.

If you are interested in advanced topics about Module Federation I recommend you to take a look at our [blog at Valor Software](https://valor-software.com/articles). I hope it helped you

**Comment by ScriptedAlchemy** [comment]
you can dynamic import from remote, but the issue here might be images are relative urls - so its loading from the wrong origin, i think file-loader and url-loader allow for public path or postTransformPublic path which lets you use some runtime logic to infer the origin of a resource. 

some loaders have public-path: auto support so they just use the url of the script currently injecting them as its base path. This is how module federation remotes load chunks without hard-coded public paths. 

Youd likey want a similar option for other static assets

**Comment by patricklafrance** [comment]
Dynamic imports in a remote module were not working for me neither with a webpack production build. To fix it, I had to set the `chunkIds` optimization to `named`.

```
{
    optimization: {
         chunkIds: "named"
    }
}
```

**Comment by patricklafrance** [comment]
@ScriptedAlchemy just wondering if there's a better alternative than forcing the `chunkIds` to be `named` ? To be honest, I dont understand why it works with named `chunkIds`, I stumbled upon this fix while removing webpack production optimizations one by one in order to debug the issue.
