### ISSUE TITLE
Many entries in webpack but only want use some of them

### ISSUE THREAD

**Issue by GTRgoSky** [module-federation/module-federation-examples#2826]
In my webpack config i have many entries like this:
```js
modules.exports = {
  entry: {
        a-file: 'xxx.js',
        b-file: 'xxxx.js'
    },
   plugin: [
      new ModuleFederationPlugin({
          name: 'app1',
          filename: 'remoteEntry.js',
          remote: {
             xxx: 'xxxxx.js'
          }
        })
  ]
}
```

I just want load **remoteEntry.js** in **a-file**, and do not load **remoteEntry.js** in **b-file.**
But i do not  know how can do these. 
If have any ignore config or plugin can control entry.

Actually , I don't want to use **import ('bootstrap. js')**  in the b-file because it should not be affected.

Can anyone help me Thx~

**Comment by ScriptedAlchemy** [comment]
Module federation does not play nicely with multiple entrypoints, im not sure if you can opt out because it adds stuff to the webpack runtime which can be in any entrypoint. 

I generally do not use multiple entries with federation, if i need other entries ill expose them and access them via remoteEntry as needed. 

Youd have to use import(bootstrap) either way, if you want it to behave wildly different between entrypoints then youd be better off with a multiCompiler and two separate builds
