### ISSUE TITLE
Support  @module-federation/client not found 

### ISSUE THREAD

**Issue by Pravin9982** [module-federation/module-federation-examples#2942]
### Discussed in https://github.com/module-federation/module-federation-examples/discussions/577

<div type='discussions-op-text'>

<sup>Originally posted by **Pravin** April 10, 2023</sup>
I am having an issue with installing module-federation/client
I am currently learning how to use webpack and module federation. I have build a simple calculator app and a container app with create-mf-app.It worked when i try to import the calculator component into the container app but now i am trying to import it into an existing react application but i am faced with an error saying that calculator falls outside the project directory. I have set up the relevent files such as webpack.config in my existing react app which i want to import the calculator component but i ask chatgpt and it says that i need to install module-federation/client for it to work. The existing react app is built with "create-react-app" and the calculator&container is built with create-mf-app. I am using react and nodejs . Bellow is the error i am getting :</div>
<img>
![image](https://user-images.githubusercontent.com/64627871/230824401-7f88d664-5fb0-45c6-9446-d55c5fca0185.png)
<img>

<div> bellow is the webpack.config for the existing react app that i am trying to import my micro frontend component:<div>

![image](https://user-images.githubusercontent.com/64627871/230840557-22dc337a-aa92-442c-b453-071c3df0e570.png)

<div> bellow is the webpack.config for the calculator micro frontend component : <div>

![image](https://user-images.githubusercontent.com/64627871/230840714-b97050e4-6d66-4de1-ac7c-032d68d4d2d2.png)

<div>Please Help and thank you for your time.<div>

**Comment by Pravin9982** [comment]
sorry forgot to tag you @ScriptedAlchemy

**Comment by khoand3012** [comment]
You should use `import Calculator from "calculatormf/Calculator"` instead of  `"../../calculator/src/Calculator"`. What you are doing is passing a relative path to the module, which only works with modules of the same local scope (everything inside your src folder). It doesn't work for remote modules, as Module Federation doesn't work like that.

And by the way, just stop asking ChatGPT about this thing, because the data that was used to train it only spans until 2021, which means everything created from 2022 (including Module Federation latest updates) onwards is outside of its knowledge domain. If you ask about something it doesn't know, it will make up fake answers that don't work at all, and fake libraries that doesn't exist. Don't trust everything ChatGPT say and remember to fact check its answers.

**Comment by Pravin9982** [comment]
hey @khoand3012 thanks for the reply.
I have tried what you have suggested but i seem to get the same error.
Bellow is the todo.js file which is where i am trying to import the calculator component :
![image](https://user-images.githubusercontent.com/64627871/232361795-8d4f3170-574e-4e76-8325-331c11bf7731.png)
This is how i am calling it in the return statement :
![image](https://user-images.githubusercontent.com/64627871/232361880-7237c2c3-478c-40d4-935c-46a99301546b.png)

But i am running into the same error :
![image](https://user-images.githubusercontent.com/64627871/232362016-eef58ab3-36b1-4243-891b-40ed621f3357.png)

For some reason it is still looking for it in the local path
Btw noted on asking chatGPT for this issue...It has got me running in circles :X

This is my github repo if you want to have a look :
https://github.com/Pravin9982/rxjsdashboard.git

Hope to hear from you soon and thank you for your time.

**Comment by khoand3012** [comment]
I had a look at your repo and saw some points worth noticing:
- You are using react-scripts instead of webpack. You should try something like this in your package.json:
![image](https://user-images.githubusercontent.com/32890161/232365758-87657a8c-fa19-4ad3-8ec4-ff8cf265197f.png)
- Try making a bootstrap file for your index.js file in the same folder.
![image](https://user-images.githubusercontent.com/32890161/232365947-e5fe0a7d-2b43-417a-8172-bafd57a90d2c.png)
- Declare an entry and output in your webpack config file, for example something like this:
![image](https://user-images.githubusercontent.com/32890161/232366405-3db98c2e-2888-4475-b040-a9437393fc18.png)
