### ISSUE TITLE
Must the public path for remoted be set to auto?

### ISSUE THREAD

**Issue by HelenSilas** [module-federation/module-federation-examples#3105]
必须设置remote的publicPath为auto吗？
现在遇到问题remote的publicPath为其他值，再使用的时候报错404

**Comment by yinjialu** [comment]
可以参考下这个：https://github.com/module-federation/module-federation-examples/pull/2170

**Comment by ScriptedAlchemy** [comment]
its recommended so that you do not have to hard-code absolute paths and instead can have webpack automatically resolve its path dynamically. However it is not required, just much less of a hassle. 

public path should either be "auto" or "http://" it cannot be relative like "/static" it would need to be "http:localhost:888/static"
