### ISSUE TITLE
esm module ends in a reference error

### ISSUE THREAD

**Issue by wibed** [module-federation/module-federation-examples#3108]
### based on: https://github.com/module-federation/module-federation-examples/tree/master/react-18-ssr

repro
https://github.com/wibed/mfExample

error:
```
ReferenceError: require is not defined
    at file:///workspace/jahe/bigbird/mfExample/shell/dist/server/main.js:1:6229
    at new Promise (<anonymous>)
    at d.f.readFileVm (file:///workspace/jahe/bigbird/mfExample/shell/dist/server/main.js:1:6173)
    at file:///workspace/jahe/bigbird/mfExample/shell/dist/server/main.js:1:2123
    at Array.reduce (<anonymous>)
    at d.e (file:///workspace/jahe/bigbird/mfExample/shell/dist/server/main.js:1:2101)
    at d.x (file:///workspace/jahe/bigbird/mfExample/shell/dist/server/main.js:1:7603)
    at file:///workspace/jahe/bigbird/mfExample/shell/dist/server/main.js:1:7626
    at ModuleJob.run (node:internal/modules/esm/module_job:192:25)
    at async DefaultModuleLoader.import (node:internal/modules/esm/loader:228:24)
```

i have stripped the example down to its bones and icorporated esm.
yet i fail to get it started.
additionally to the usual things i tried:
##### webpack settings, (wherever possible)
- `experiments: { outputModule: true }`
- `library: { type: 'module' }`
- `libraryTarget: "module"`
- `chunkFormat: "module"`
- `devtool: 'inline-source-map'`
- removed json import `dependencies` within module federation config
  and set it to `{ singleton: true }`
- using an alias to destructure an async import (where from the error message i assume the source relies)
- updated webpack as well as it subcomponents to latest version

i must be missing something. would appreciate a hint

**Comment by wibed** [comment]
obviously, `optimization: { chunks: 'initial' } }`
does prevent esm from loading.

change it to `optimization: { splitChunks: false || 'async' }
and it should work 

it does until you make the first request.
```jsx
file:///workspace/jahe/bigbird/mfExample/shell/dist/server/main.js:1923
/******/                                                var filename = require('path').join(__dirname, "" + __webpack_require__.u(chunkId));
                                                                       ^

ReferenceError: require is not defined
    at file:///workspace/jahe/bigbird/mfExample/shell/dist/server/main.js:1923:31
    at new Promise (<anonymous>)
    at __webpack_require__.f.readFileVm (file:///workspace/jahe/bigbird/mfExample/shell/dist/server/main.js:1921:29)
    at file:///workspace/jahe/bigbird/mfExample/shell/dist/server/main.js:1549:39
    at Array.reduce (<anonymous>)
    at __webpack_require__.e (file:///workspace/jahe/bigbird/mfExample/shell/dist/server/main.js:1548:66)
    at Object.get (file:///workspace/jahe/bigbird/mfExample/shell/dist/server/main.js:1642:82)
    at get (file:///workspace/jahe/bigbird/mfExample/shell/dist/server/main.js:1732:25)
    at getSingletonVersion (file:///workspace/jahe/bigbird/mfExample/shell/dist/server/main.js:1697:19)
    at file:///workspace/jahe/bigbird/mfExample/shell/dist/server/main.js:1777:19
```


NOTE:
this occurs after setting the mode for server from `production` to `development`

**Comment by ScriptedAlchemy** [comment]
I dont support ESM for several reasons. Ill update the plugin to that it fails the build right from the start if a user attempts to configure incorrect target outputs. 

It must be commonjs-module and commonjs-module only.

**Comment by wibed** [comment]
i ask myself if using a transpiler like babel-loader would make a hybrid approach possible.
updated my reproduction
including
```jsx
use: [
          {
            loader: "babel-loader",
            options: {
              plugins: [
                ["@babel/plugin-transform-modules-commonjs", { allowTopLevelThis: true }]
              ],
              presets: [
                "@babel/preset-react",
                "@babel/preset-typescript"
              ]
            }
          }
        ],
```
got it to load on development mode. BUT it crashes on the first request as before.

**Comment by ScriptedAlchemy** [comment]
It's not about your code being ESM or not. So loader isn't the issue. It's that webpack itself will emit esm chunks and use ESM chunk loading patterns on the server which wouldn't work since import(http) isn't a supported feature and if it were, I can't hot reload it in prod because there's no require cache. 

I need webpack itself to use commonjs loading patterns for requiring its outputted chunks since ESM can't be wrapped into vm.runInThisContext 

ESM isn't a script like commonjs is - so it's harder to evaluate. 

To support netlify edge which is ESM and deno, I had the same problem and had to use the wrap method there as well. 

I did come across a possible solution but think it was for browsers so I'm not sure if it works for servers. 

But, regardless - ESM output target would require a completely separate plugin to be built. Since if you look at my source you'll see it's very specific to the chunk loading format. For ESM id have to copy paste the webpack esm chunk loading system out and rewrite it to support whatever would work for non filesystem imports as well as its normal filesystem imports. 

It's got a very low ROI since there's no reason server needs to be esm over commonjs beyond philosophical opinion haha. You can use ESM output in browser no problem, but keep server in commonjs till it's feasible to support. 

If ESM support lands, I might implement it in rspack first since we have full control over rspack and would not need to ship another npm package but could just bake all this right into the compiler to begin with
