### ISSUE TITLE
Directly navigate from app1 to app2 (not from the shell)

### ISSUE THREAD

**Issue by idonava** [module-federation/module-federation-examples#3178]
Hello,
I built a new application based on Module federation, react and react-router-dom (based on https://github.com/module-federation/module-federation-examples/tree/master/react-nested-routers)

My application contains 3 MFEs:
1. Shell (localhost:3000/)
2. App1 (localhost:3000/app1)
3. App2 (localhost:3000/app2)

I have a Navigation bar in the shell MFE app, and I can easily redirect between app1 & app2 based on the shell MFE.

Now, I want to navigate from App2 to App1 without being dependent on the shell Navigation bar (Imagine a situation of clicking a button in App2 will redirect into App1 with some parameters).

Is there an option to do it? 

Thanks!

**Comment by RussellCanfield** [comment]
Have you tried creating a sort of empty route in app2 and use an absolute path in the Link component? Nested routers is kind of messy

**Comment by haimrait** [comment]
Hey @RussellCanfield 
For my understanding what @idonava trying to do is that:
regarding his [example](https://github.com/module-federation/module-federation-examples/tree/master/react-nested-routers)

Original Code: `app2/src/pages/PageA.tsx`
```
<React.Fragment>
    <div>Page A from App2</div>
    <Link to="/page-b">Go to Page B</Link>
 </React.Fragment>
```

@idonava  Code: `app2/src/pages/PageA.tsx`
```
<React.Fragment>
    <div>Page A from App2</div>
    <Link to="/page-b">Go to Page B</Link>
    <Link to="/app-1/page-2">Go to App 1</Link>
 </React.Fragment>
```
throws 404

I found a that if we change the link from `Link` to `<a>` works fine but I dont know if its suitable solution.
```
<React.Fragment>
    <div>Page A from App2</div>
    <Link to="/page-b">Go to Page B</Link>
    <a href="/app-1/page-2">Go to App 1</a>
 </React.Fragment>
```
Works fine, maybe because it is overcome App2 local react router.

**Comment by ScriptedAlchemy** [comment]
Either needs a parent router who understands or you need to inject it into a router somehow. usually parent switch with appnames work, centrali router thats federated from shell back to MFE when running standalone

**Comment by idonava** [comment]
I fixed it by a
