### ISSUE TITLE
What if not use "shared" in host app

### ISSUE THREAD

**Issue by matthewma7** [module-federation/module-federation-examples#374]
Thank you for this great invention. It opens up so much possibilities!

For the basic-host-remote example, it looks like I can comment out the whole [shared config](https://github.com/module-federation/module-federation-examples/blob/ea73f45b8dd8000e3a18165d00c38a286e5e64bf/basic-host-remote/app1/webpack.config.js#L41) and I also change to **not** use bundle-loader or dynamic import, the `app button2` still works fine, so what have happen when I did those change? Is this ok thing to do if I don't need omnidirectional host?

**Comment by ScriptedAlchemy** [comment]
Sure. So you can choose not to share. But in doing to you'll load multiple copies of the same dependency, a major problem for stuff like react. You only need a import bootstrap if you're sharing something in the entrypoint that's not dynamically imported. If you async imported all the shared modules. Or didn't share, webpack won't have async issues because it's shipping it's own vendors and you're not orchestrating shared code between the apps runtimes. If you added a hook to the remote component. It likely would throw a react error since react needs to be a singleton
