### ISSUE TITLE
app header script is Dynamic injection

### ISSUE THREAD

**Issue by xileliu** [module-federation/module-federation-examples#49]
main application:
1. ![image](https://user-images.githubusercontent.com/13429648/82108427-edc53380-9760-11ea-96b4-19aebc6928be.png)
2. bootstrap.js  support？
![image](https://user-images.githubusercontent.com/13429648/82108468-26650d00-9761-11ea-8215-652770c8435b.png)

**Comment by maraisr** [comment]
Hello 👋 thanks for the issue!! 💯  Can you please elaborate more on what you're finding the issue to be?

**Comment by ScriptedAlchemy** [comment]
Doesn’t look like our code. Yes you can do dynamic injections. We also have a repo in there that does it dynamic-system or something. 

You need done kind of promise chain to know when the script is loaded. Otherwise race conditions can occur. This also would increase RTT but is useful for dynamic federation. You may have problems with sharing vendor code as overrides are built into the webpack parser. You’d have to do them manually for right now
