### ISSUE TITLE
Sharing React Context as Service not working

### ISSUE THREAD

**Issue by arkroy** [module-federation/module-federation-examples#732]
Hi

I'm trying to build a react microfrontend application which exposes a context as service to other microFEs along with other UI elements. The implementation is similar to the shared-routing example - the service.js part of it. However I it throws an error while loading the context in the browser - 

TypeError: Cannot read property 'default' of undefined
TypeError: (0, e.default) is not a function. 

Other UI elements exposed work and load up fine. I'm using Webpack 5.21.2 with React 17.0.1. 

Is context sharing no longer supported? I bought the book and it doesn't speak much about react context. Is there a plan to update the examples ? Could you help?

**Comment by ScriptedAlchemy** [comment]
id need to see a repo but it looks like you need to include the hosts own remote on the page, since you're both exposing and sharing something, it's technically not available based on how shareScope works under the hood, at bootup. 

So the host depends on its own remote to load something similar to `service`, since we are vending it entirely as a federated module. notice how my shared routing, the shell, port 3000 remote is included on all apps since it needs to load its own remote to require this totally federated module.
